project:
  type: website

website:
  title: "DZA day"
  announcement: 
    icon: info-circle
    dismissable: true
    content: "Join us to DZA days Leuven on **4<sup>th</sup> of November 2024**"
    type: light
    position: below-navbar
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: sponsors.qmd
        text: Sponsors
      - href: program.qmd
        text: Program
      - href: location.qmd
        text: How to get there
      - href: abstract.qmd
        text: Abstract submission
      - href: registration.qmd
        text: Registration

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

execute:
  freeze: auto